controller_server:
  # 0：Pure Pursuit，1：MPC，2：LQR
  controller_type: 0
  rate: 50.0

  finish_error_log_path: "/home/lfh/SLAM+PNC/PNC/src/controller/finish_error_log.txt"
  finish_average_frames: 20

  max_forward_linear_velocity: 1.2
  max_backward_linear_velocity: -1.2
  max_angular_velocity: 0.4
